#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Badtomcat\Framework\Command\ShowVersion;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new ShowVersion());
$application->run();